# Generated by Django 5.2.6 on 2025-11-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/%d/'),
        ),
    ]
