# Generated by Django 5.2.8 on 2025-11-14 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_creator_course_coursesupervisor_and_more'),
        ('daily_reports', '0002_alter_dailyreport_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AlterUniqueTogether(
            name='coursesupervisor',
            unique_together={('course', 'supervisor')},
        ),
    ]
