# Generated by Django 5.2.7 on 2025-11-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_creator_course_coursesupervisor_and_more'),
        ('daily_reports', '0002_alter_dailyreport_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AlterUniqueTogether(
            name='coursesupervisor',
            unique_together={('course', 'supervisor')},
        ),
    ]
