# Generated by Django 5.2.6 on 2025-11-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskable_type',
            field=models.IntegerField(choices=[(0, 'Subject'), (1, 'CourseSubject')]),
        ),
    ]
