# Generated by Django 5.2.6 on 2025-11-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_task_options_task_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='estimated_time_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
